let g:coc_global_extensions = [
  \ 'coc-snippets',
  \ 'coc-eslint',
  \ 'coc-emmet',
  \ 'coc-vetur',
  \ 'coc-tsserver',
  \ 'coc-phpls',
  \ 'coc-json',
  \ 'coc-html',
  \ 'coc-css',
  \ 'coc-sh',
  \ 'coc-sql',
  \ 'coc-python',
  \ 'coc-prettier',
  \ ]